[package]
name = "jwt_auth"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.1", features = ["full"] }
jsonwebtoken = "9.3.0"
axum = "0.7.5"
serde = "1.0.204"
serde_json = "1.0.120"
chrono = "0.4.38"